### PR TITLE
Fixes to make sure that VFPT color scheme updates properly when VS theme is changed

### LINKED ISSUE #1359: F# Power Tools color scheme does not adjust when Visual Studio color scheme is changed
### Description

F# Power Tools color scheme does not adjust when Visual Studio color scheme is changed.

### Repro steps

Please provide the steps required to reproduce the problem

1. Uninstall F# Power Tools.
2. Set Visual Studio color theme to blue.
3. Install F# Power Tools.
4. Set Visual Studio color theme to dark.

### Expected behavior

F# Power Tools color scheme adjusts to match Visual Studio color scheme.

### Actual behavior

F# Power Tools color scheme does not adjust, making many words unreadable (see screenshot).

image

### Known workarounds

Uninstall, then reinstall the extension. (disable, then enable, does not help)

### Related information 

* Operating system: Windows 10 Insider Preview
* Branch: Version 2.3.0 on Visual Studio 2015 Update 1

### PR DESCRIPTION
**Pull request by surban**
Fixes #1359

### CODE REVIEW

File: src/FSharpVSPowerTools/Commands/PrintfSpecifiersUsageTaggerProvider.cs [hunk 1]
```diff
@@ -41,11 +41,12 @@ public class PrintfSpecifiersUsageTaggerProvider : IViewTaggerProvider, IDisposa
             _printfColorManager = printfColorManager;
 
             VSColorTheme.ThemeChanged += UpdateTheme;
+            _printfColorManager.UpdateColors(true);
```
Comment (dungpa) [inline src/FSharpVSPowerTools/Commands/PrintfSpecifiersUsageTaggerProvider.cs]: Could you use named parameters e.g. `force: true` to make boolean arguments clear?

This comment applies to other invocations of `UpdateColors` as well.

File: src/FSharpVSPowerTools/Commands/PrintfSpecifiersUsageTaggerProvider.cs [hunk 2]
```diff
@@ -89,22 +91,27 @@ public PrintfColorManager(ThemeManager themeManager, IEditorFormatMapService edi
...
-        public void UpdateColors()
+        public void UpdateColors(bool force)
         {
             var newTheme = _themeManager.GetCurrentTheme();
 
-            if (newTheme != VisualStudioTheme.Unknown && newTheme != _currentTheme)
+            // Multiple theme change events are fired in rapid succession after the theme was changed.
+            // All of them must be processed to properly update the color scheme.
+            if (newTheme != VisualStudioTheme.Unknown &&
+                (newTheme != _currentTheme || (_lastThemeChange - DateTime.Now).TotalSeconds < 10 || force))
```
Comment (dungpa) [inline src/FSharpVSPowerTools/Commands/PrintfSpecifiersUsageTaggerProvider.cs]: This condition is always true because `_lastThemeChange <= DateTime.Now`, isn't this?

Or do you mean `DateTime.Now - _lastThemeChange` here?

File: src/FSharpVSPowerTools/Commands/SymbolClassifiersProvider.cs [hunk 3]
```diff
@@ -166,17 +168,23 @@ public FontColor GetDefaultColors(string category)
...
         {
             var newTheme = _themeManager.GetCurrentTheme();
 
-            if (newTheme != VisualStudioTheme.Unknown && newTheme != _currentTheme)
+            LoggingModule.logInfoMessage(() => String.Format("Color theme changed from {0} to {1}.", _currentTheme, newTheme));
+
+            // Multiple theme change events are fired in rapid succession after the theme was changed.
+            // All of them must be processed to properly update the color scheme.
+            if (newTheme != VisualStudioTheme.Unknown && 
+                (newTheme != _currentTheme || (_lastThemeChange - DateTime.Now).TotalSeconds < 10) || force)
```
Comment (dungpa) [inline src/FSharpVSPowerTools/Commands/SymbolClassifiersProvider.cs]: Similar comment as above.

**Comment by surban** [comment]
Thanks for the review. I made the changes you requested.

**Comment by dungpa** [comment]
The changes look good. Unfortunately, a few unit tests fail with NRE on Windows.

Here are the relevant lines:

https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.VisualStudio.Tests/SymbolClassifierTests.fs#L19

https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.VisualStudio.Tests/SymbolClassifierTests.fs#L19

They can be fixed by providing suitable mocks for those values. See https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.VisualStudio.Tests/Mocks.fs#L21-L43 for an example.

Would you mind to adjust unit tests? 
Thank you.

**Comment by surban** [comment]
I tried to add a mock for ClassificationColorManager, however I still get null reference exceptions related to this type. I am not familiar with Foq. Can you help?

**Comment by dungpa** [comment]
Sorry, the test infra is really brittle.

You should create the mock objects in VsTestBase like others https://github.com/surban/VisualFSharpPowerTools/blob/dee4d51707e28339a29b8db07577229def44ab3a/tests/FSharp.Editing.VisualStudio.Tests/VsTestBase.fs#L38-L45 or remove this Dispose call https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.VisualStudio.Tests/SymbolClassifierTests.fs#L45.

By the way, the similar change should be done for https://github.com/fsprojects/VisualFSharpPowerTools/blob/03c613acd3aa67cb5e3a339d3dcf1c7c783f30c2/tests/FSharp.Editing.VisualStudio.Tests/PrintfSpecifiersUsageTaggerTests.fs#L17.

**Comment by dungpa** [comment]
I don't know why Foq fails to initialize `ClassificationColorManager` instances. You could comment out SymbolClassifierTests for now.

**Comment by surban** [comment]
The problem was that UpdateColors was not virtual. The mocks are working now.

**Comment by dungpa** [comment]
Great work. Thanks for your persistence.

**Comment by vasily-kirichenko** [comment]
Published in 2.5.5.

**Comment by vasily-kirichenko** [comment]
@surban do you mind to fix #1479? If you don't, please make a PR which rollbacking this PR.
